kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: backend
    image: maven:3-jdk-11
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package

  - name: frontend
    image: node:16-alpine
    commands:
      - cd web
      - npm i && npm run build

  - name: push
    image: hosppy/docker:alpine
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_REPO:
        from_secret: DOCKER_REPO
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - bash ./scripts/push.sh

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: DINGTALK_TOKEN
      type: markdown

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /var/run/docker.sock
