version: '3.7'

services:
  account-service:
    build: account-svc
    image: hosppy/account-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - ACCOUNT_DATASOURCE_URL
      - ACCOUNT_DATASOURCE_USERNAME
      - ACCOUNT_DATASOURCE_PASSWORD
      - EMAIL_SERVICE_ENDPOINT
      - WEB_DOMAIN
    depends_on:
      - email-service
    networks:
      - internal_access
      - external_access
  email-service:
    build: email-svc
    image: hosppy/email-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - ALIYUN_ACCESS_KEY
      - ALIYUN_ACCESS_SECRET
      - MAIL_FROM
      - MAIL_FROM_NAME
    networks:
      - internal_access
      - external_access
  planck-service:
    build: planck
    image: hosppy/planck-svc
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - ACCOUNT_SERVICE_ENDPOINT
    depends_on:
      - account-service
    networks:
      - internal_access
      - external_access
  web-service:
    build: web
    image: hosppy/web
    ports:
      - "80:80"
    depends_on:
      - planck-service
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access: