spring:
  profiles:
    active: dev
  datasource:
    url: ${HOSPITAL_DATASOURCE_URL}
    username: ${HOSPITAL_DATASOURCE_USERNAME}
    password: ${HOSPITAL_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false