server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: ${ACCOUNT_SERVICE_ENDPOINT:http://localhost:8002}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

hosppy:
  signing-secret: ${SIGNING_SECRET:signing-secret}