spring:
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: ${ACCOUNT_SERVICE_ENDPOINT}
          predicates:
            - Path=/api/**
            filters:
              - StripPrefix=1
