version: '3.7'

services:
  web:
    image: ${DOCKER_IMAGE}:${TAG}
    env_file: .env
    ports:
      - "9090:8080"
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access: