version: '3.7'

services:
  app:
    image: ${DOCKER_IMAGE_APP}:${TAG}
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - internal_access
      - external_access
  web:
    image: ${DOCKER_IMAGE_WEB}:${TAG}
    env_file: .env
    ports:
      - "9090:8080"
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access: