-- Create "account" table
CREATE TABLE "account" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "name" character varying NOT NULL DEFAULT '',
  "phone_number" character varying NOT NULL,
  "active" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "password_hash" character varying NULL DEFAULT '',
  "avatar_url" character varying NULL DEFAULT '',
  PRIMARY KEY ("id")
);
-- Create index "account_email_key" to table: "account"
CREATE UNIQUE INDEX "account_email_key" ON "account" ("email");
-- Create index "account_phone_number_key" to table: "account"
CREATE UNIQUE INDEX "account_phone_number_key" ON "account" ("phone_number");
