name: Build
run-name: Build
on: [ push ]
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
      - run: docker built -t hosppy:latest .