name: publish
on: [ push ]
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - run: ./gradlew bootJar --no-daemon

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/hosppy/web:${{ steps.commit.outputs.short }}

      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./publish/docker-compose-template.yml
          target: ./
          strip_components: 2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        env:
          DOCKER_IMAGE: ${{ secrets.REGISTRY_URL }}/hosppy/web
          TAG: ${{ steps.commit.outputs.short }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: DOCKER_IMAGE,TAG
          script: |
            sed -e "s,\${DOCKER_IMAGE},$DOCKER_IMAGE,g" -e "s,\${TAG},$TAG,g" docker-compose-template.yml > docker-compose.yml
            docker-compose up -d --force-recreate
