name: publish
run-name: Publish hosppy development env
on: [ push ]
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Docker build
        run: docker build -t hosppy/svc .
