name: CI
run-name: ${{ github.actor }} is testing out Github Actions
on: [ push ]
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
        run: ./gradlew clean bootJar

      - name: Docker build
        run: docker build -t hosppy/svc .
